// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX6kdzzcPnYl_Ru1ntXrOTkrW24AMp_sk',
    appId: '1:414975106996:web:4510f9afe053b7177d9ce1',
    messagingSenderId: '414975106996',
    projectId: 'mofiloapp-3f175',
    authDomain: 'mofiloapp-3f175.firebaseapp.com',
    storageBucket: 'mofiloapp-3f175.appspot.com',
    measurementId: 'G-D2GRRH2NWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClTDn7WZrxXWtYrX1l5AiH3HqNdipEPts',
    appId: '1:414975106996:android:2efdc93b2a9ddef07d9ce1',
    messagingSenderId: '414975106996',
    projectId: 'mofiloapp-3f175',
    storageBucket: 'mofiloapp-3f175.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhPzsLnvchNKcnDn8fOFCfULGSefxfW9A',
    appId: '1:414975106996:ios:c479daaa81b5d9ce7d9ce1',
    messagingSenderId: '414975106996',
    projectId: 'mofiloapp-3f175',
    storageBucket: 'mofiloapp-3f175.appspot.com',
    iosBundleId: 'com.example.mobileappSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhPzsLnvchNKcnDn8fOFCfULGSefxfW9A',
    appId: '1:414975106996:ios:c479daaa81b5d9ce7d9ce1',
    messagingSenderId: '414975106996',
    projectId: 'mofiloapp-3f175',
    storageBucket: 'mofiloapp-3f175.appspot.com',
    iosBundleId: 'com.example.mobileappSetup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX6kdzzcPnYl_Ru1ntXrOTkrW24AMp_sk',
    appId: '1:414975106996:web:47c622e41aff187c7d9ce1',
    messagingSenderId: '414975106996',
    projectId: 'mofiloapp-3f175',
    authDomain: 'mofiloapp-3f175.firebaseapp.com',
    storageBucket: 'mofiloapp-3f175.appspot.com',
    measurementId: 'G-K8K8X5RZH3',
  );
}
